# Numpy

This notebook is a compilation of courses and tutorials taken. Its goal is to contain most of the relevant operations used in Numpy for data science.


#### Import NumPy as np

In [1]:
import numpy as np

### Create Numpy arrays

#### From a Python List

In [4]:
# using a python list
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### arange
Return evenly spaced values within a given interval.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### zeros and ones

Generate arrays of zeros or ones

In [4]:
# create an array of 10 zeros
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [8]:
# create a 5x5 matrix of zeros
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [9]:
# create an array of 10 ones
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [10]:
# create a 5x5 matrix of ones
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [11]:
# from 0 to 10, 3 samples to generate - default number is 50
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [13]:
np.linspace(0,10,10)

array([  0.        ,   1.11111111,   2.22222222,   3.33333333,
         4.44444444,   5.55555556,   6.66666667,   7.77777778,
         8.88888889,  10.        ])

## eye

Creates an identity matrix#### Create an array of the integers from 10 to 50

In [14]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [17]:
np.random.rand(10)

array([ 0.65819285,  0.57316432,  0.16873739,  0.89732879,  0.34416648,
        0.0932349 ,  0.82237783,  0.83326191,  0.27979072,  0.80690368])

In [16]:
np.random.rand(5,5)

array([[ 0.15261297,  0.45227316,  0.34817217,  0.19338929,  0.27390204],
       [ 0.79108804,  0.76940919,  0.56238878,  0.73888298,  0.04937816],
       [ 0.6914478 ,  0.18423087,  0.89579363,  0.55107475,  0.69011169],
       [ 0.44904409,  0.48802251,  0.85150952,  0.78443349,  0.11029643],
       [ 0.80988459,  0.13872695,  0.38950097,  0.59494795,  0.21494329]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [18]:
np.random.randn(10)

array([-0.73568877, -0.02203118,  0.88314166,  0.27104452,  0.86518823,
        0.77623019,  0.505599  , -0.68522492,  1.10142949,  1.3191286 ])

In [19]:
np.random.randn(5,5)

array([[ 0.70800728, -1.69635454, -1.08464963,  0.68680864, -0.21686833],
       [ 0.19959582, -0.89166171, -1.32513179,  0.33383294,  1.68078769],
       [ 0.13306695, -2.50308649, -0.44916506,  0.22243163,  0.6409702 ],
       [ 0.1884421 ,  1.54298569, -0.7992658 ,  1.45969674,  0.31716033],
       [ 0.11268022,  0.35340949, -0.86207252,  0.19320358,  0.63730683]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [20]:
np.random.randint(1,100)

59

In [23]:
# 10 random ints between 1 and 10
np.random.randint(1,100,10)

array([69, 84, 10, 70, 42, 96, 39, 43, 42, 16])

## Array Attributes and Methods

Some useful attributes and methods or an array:

In [24]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

## Reshape
Returns an array containing the same data with a new shape.

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [28]:
ranarr

array([33, 49, 28, 32, 41, 45, 49, 30, 38, 44])

In [29]:
ranarr.max()

49

In [30]:
ranarr.argmax()

1

In [31]:
ranarr.min()

28

In [32]:
ranarr.argmin()

2

## Shape

Shape is an attribute that arrays have (not a method):

In [34]:
x = np.array([1, 2, 3, 4])
x.shape

(4,)

In [35]:
y = np.zeros((2, 3, 4))
y.shape

(2, 3, 4)

### dtype

You can also grab the data type of the object in the array:

In [37]:
arr.dtype

dtype('int64')

#### Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [15]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### Use NumPy to generate a random number between 0 and 1

In [49]:
np.random.rand(1)

array([ 0.58770156])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [50]:
np.random.randn(25)

array([ 0.18290785, -2.0216631 ,  0.46554157, -1.01017523,  1.49751998,
       -0.70146109,  0.3850237 ,  0.40425833, -0.72385984,  1.12251243,
        2.56127003,  0.79584691, -1.14648782,  1.17961535, -0.58353361,
        1.13021755, -1.79166359,  1.98112752,  0.433385  ,  1.76872336,
       -1.39360854, -0.00878735, -0.23140773, -1.21844153,  0.34840488])

#### Create the following matrix:

In [35]:
np.arange(0.01, 1.01, 0.01).reshape(10,10)

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [30]:
np.linspace(0.0,1.0, num=20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [32]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [36]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [39]:
mat[3][-1]

20

In [42]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE


array([[ 2],
       [ 7],
       [12]])

In [42]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [43]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE


array([21, 22, 23, 24, 25])

In [44]:
mat[-1]

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [45]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [46]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [47]:
np.std(mat)

7.2111025509279782

#### Get the sum of all the columns in mat

In [48]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])

# Great Job!