# Numpy

This notebook is a compilation of courses and tutorials taken. Its goal is to contain most of the relevant operations used in Numpy for data science.


#### Import NumPy as np

In [2]:
import numpy as np

### Create Numpy arrays

#### From a Python List

In [4]:
# using a python list
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### arange
Return evenly spaced values within a given interval.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### zeros and ones

Generate arrays of zeros or ones

In [4]:
# create an array of 10 zeros
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [8]:
# create a 5x5 matrix of zeros
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [9]:
# create an array of 10 ones
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [10]:
# create a 5x5 matrix of ones
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [11]:
# from 0 to 10, generate 3 samples - default number is 50
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [13]:
np.linspace(0,10,10)

array([  0.        ,   1.11111111,   2.22222222,   3.33333333,
         4.44444444,   5.55555556,   6.66666667,   7.77777778,
         8.88888889,  10.        ])

## eye

Creates an identity matrix#### Create an array of the integers from 10 to 50

In [14]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [17]:
np.random.rand(10)

array([ 0.65819285,  0.57316432,  0.16873739,  0.89732879,  0.34416648,
        0.0932349 ,  0.82237783,  0.83326191,  0.27979072,  0.80690368])

In [16]:
np.random.rand(5,5)

array([[ 0.15261297,  0.45227316,  0.34817217,  0.19338929,  0.27390204],
       [ 0.79108804,  0.76940919,  0.56238878,  0.73888298,  0.04937816],
       [ 0.6914478 ,  0.18423087,  0.89579363,  0.55107475,  0.69011169],
       [ 0.44904409,  0.48802251,  0.85150952,  0.78443349,  0.11029643],
       [ 0.80988459,  0.13872695,  0.38950097,  0.59494795,  0.21494329]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [18]:
np.random.randn(10)

array([-0.73568877, -0.02203118,  0.88314166,  0.27104452,  0.86518823,
        0.77623019,  0.505599  , -0.68522492,  1.10142949,  1.3191286 ])

In [19]:
np.random.randn(5,5)

array([[ 0.70800728, -1.69635454, -1.08464963,  0.68680864, -0.21686833],
       [ 0.19959582, -0.89166171, -1.32513179,  0.33383294,  1.68078769],
       [ 0.13306695, -2.50308649, -0.44916506,  0.22243163,  0.6409702 ],
       [ 0.1884421 ,  1.54298569, -0.7992658 ,  1.45969674,  0.31716033],
       [ 0.11268022,  0.35340949, -0.86207252,  0.19320358,  0.63730683]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [20]:
np.random.randint(1,100)

59

In [23]:
# 10 random ints between 1 and 10
np.random.randint(1,100,10)

array([69, 84, 10, 70, 42, 96, 39, 43, 42, 16])

## Array Attributes and Methods

Some useful attributes and methods or an array:

In [24]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

## Reshape
Returns an array containing the same data with a new shape.

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [28]:
ranarr

array([33, 49, 28, 32, 41, 45, 49, 30, 38, 44])

In [29]:
ranarr.max()

49

In [30]:
ranarr.argmax()

1

In [31]:
ranarr.min()

28

In [32]:
ranarr.argmin()

2

## Shape

Shape is an attribute that arrays have (not a method):

In [34]:
x = np.array([1, 2, 3, 4])
x.shape

(4,)

In [35]:
y = np.zeros((2, 3, 4))
y.shape

(2, 3, 4)

### dtype

You can also grab the data type of the object in the array:

In [37]:
arr.dtype

dtype('int64')

# NumPy Operations

## Arithmetic

Examples of array arithmetic:

In [3]:
arr = np.arange(0,10)

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

/home/administrator/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ipykernel/__main__.py:3: RuntimeWarning: divide by zero encountered in divide
  app.launch_new_instance()


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
# Also warning, but not an error instead infinity
1/arr

/home/administrator/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ipykernel/__main__.py:2: RuntimeWarning: divide by zero encountered in divide
  from ipykernel import kernelapp as app


array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [10]:
arr+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Some common ones are:

In [12]:
#Taking Square Roots
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [13]:
#Calcualting exponential (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [14]:
np.max(arr) #same as arr.max()

9

In [15]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [16]:
np.log(arr)

/home/administrator/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458])

# NumPy Indexing and Selection

Examples how to select elements or groups of elements from an array.

In [17]:
#Creating sample array
arr = np.arange(0,11)

In [18]:
#Get a value at an index
arr[8]

8

In [19]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [20]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [21]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [22]:
# Reset array
arr = np.arange(0,11)

In [23]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [24]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [25]:
# The changes also occur in our original array!
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**.

In [27]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [29]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [30]:
# Getting individual element value
arr_2d[1,0]

20

In [31]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [32]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [33]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows to select entire rows or columns out of order:

In [34]:
#Set up matrix
arr2d = np.zeros((10,10))

#Length of array
arr_length = arr2d.shape[1]

#Set up array
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [35]:
# Fancy indexing allows
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [36]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Example:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

In [42]:
arr2d[0,3:5]

array([ 0.,  0.])

In [44]:
arr2d[1,::2]

array([ 1.,  1.,  1.,  1.,  1.])

In [38]:
arr2d[4:,4:]

array([[ 4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.]])

In [39]:
arr2d[:,2]

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [40]:
arr2d[2::2,::2]

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.]])

## Selection

Use brackets for selection based off of comparison operators.

In [45]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [48]:
bool_arr = arr>4
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [49]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])